services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - ./data:/opt/alist/data
    ports:
      - 9531:5244
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
        