services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime
    network_mode: bridge
    volumes:
      - ./data:/app/data
    ports:
      - 9532:3001
    restart: unless-stopped