services:
  shadowsocks-libev:
    container_name: shadowsocks
    network_mode: bridge
    ports:
      - 8388:8388
      - 8388:8388/udp
    environment:
      - PASSWORD=xxxxxx
      - METHOD=aes-256-gcm
    image: gists/shadowsocks-libev

