services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 9529:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
